# Generated by Django 5.1.2 on 2024-10-19 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='availability_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='availability_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='availability_ru',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_ru',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.car')),
                ('parent_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.review')),
            ],
        ),
    ]
