# Generated by Django 5.1.2 on 2024-10-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_car_availability_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='box_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='box_en_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='box_en_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='box_en_ru',
        ),
        migrations.RemoveField(
            model_name='car',
            name='box_kg',
        ),
        migrations.RemoveField(
            model_name='car',
            name='box_kg_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='box_kg_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='box_kg_ru',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_en_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_en_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_en_ru',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_kg',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_kg_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_kg_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_kg_ru',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_en_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_en_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_en_ru',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_kg',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_kg_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_kg_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rudder_kg_ru',
        ),
    ]
